from django.core.management.base import BaseCommand

from analyzer.models import IngredientReference, Product


INGREDIENT_DATA = [
    {'name': 'MSG', 'aliases': 'monosodium glutamate,flavour enhancer 621,flavor enhancer 621', 'risk_level': 'harmful', 'score_impact': -20, 'description': 'Common flavour enhancer that some users prefer to avoid in regular meals.'},
    {'name': 'Artificial Color', 'aliases': 'tartrazine,sunset yellow,allura red,caramel color,colour e150d', 'risk_level': 'harmful', 'score_impact': -18, 'description': 'Synthetic colours are a common marker of heavily processed foods.'},
    {'name': 'Preservative', 'aliases': 'sodium benzoate,potassium sorbate,bha,bht,sodium meta bisulphite', 'risk_level': 'harmful', 'score_impact': -15, 'description': 'Preservatives help shelf life but are not ideal in high-frequency diets.'},
    {'name': 'High Fructose Corn Syrup', 'aliases': 'hfcs,corn syrup', 'risk_level': 'harmful', 'score_impact': -18, 'description': 'Highly processed sweetener associated with ultra-processed foods.'},
    {'name': 'Palm Oil', 'aliases': 'palmolein,palm fat,palm oil,vegetable fat palm,rbd palm oil', 'risk_level': 'moderate', 'score_impact': -8, 'description': 'Frequently discussed in processed snacks because of heavy use and saturated fat content.'},
    {'name': 'Sugar', 'aliases': 'added sugar,sucrose,dextrose,invert syrup,invert sugar', 'risk_level': 'moderate', 'score_impact': -10, 'description': 'Too much added sugar reduces nutritional quality.'},
    {'name': 'Salt', 'aliases': 'sodium chloride', 'risk_level': 'moderate', 'score_impact': -6, 'description': 'Excess salt intake should be limited.'},
    {'name': 'Refined Flour', 'aliases': 'maida,refined wheat flour', 'risk_level': 'moderate', 'score_impact': -8, 'description': 'Highly refined flour is less nutritious than whole grain options.'},
    {'name': 'Caffeine', 'aliases': 'caffeine flavouring,caffeine', 'risk_level': 'moderate', 'score_impact': -5, 'description': 'Fine in moderation, but not ideal as a routine drink for children.'},
    {'name': 'Acidity Regulator', 'aliases': 'phosphoric acid,citric acid,acidity regulator', 'risk_level': 'moderate', 'score_impact': -4, 'description': 'Common in packaged foods and drinks; often signals processed formulation.'},
    {'name': 'Wheat Flour', 'aliases': 'atta,wheat,whole wheat', 'risk_level': 'safe', 'score_impact': 2, 'description': 'Common staple ingredient and generally considered safe.'},
    {'name': 'Milk Solids', 'aliases': 'milk powder,milk,skim milk powder,whole milk powder', 'risk_level': 'safe', 'score_impact': 3, 'description': 'Nutrient-rich dairy ingredient.'},
    {'name': 'Cocoa', 'aliases': 'cocoa solids,cocoa powder', 'risk_level': 'safe', 'score_impact': 2, 'description': 'Natural cocoa ingredient.'},
    {'name': 'Natural Flavor', 'aliases': 'natural flavour,natural flavors,natural flavouring,natural flavourings', 'risk_level': 'safe', 'score_impact': 1, 'description': 'Lower concern than clearly synthetic flavour systems.'},
    {'name': 'Oats', 'aliases': 'rolled oats,oat fiber,oats', 'risk_level': 'safe', 'score_impact': 3, 'description': 'Whole grain ingredient with fiber and better satiety.'},
    {'name': 'Tomato', 'aliases': 'tomato paste,tomato solids,tomato', 'risk_level': 'safe', 'score_impact': 2, 'description': 'Simple base ingredient with better food quality than generic flavour mixes.'},
]

PRODUCT_DATA = [
    {
        'name': 'Maggi 2-Minute Masala Noodles',
        'brand': 'Maggi',
        'category': 'Instant Noodles',
        'ingredient_text': 'Ingredients: refined wheat flour, edible vegetable oil, palm oil, salt, flavour enhancer 621, spices, sugar, onion powder, garlic powder, artificial color, acidity regulator.',
        'image_url': '/static/images/products/maggi.svg',
        'short_description': 'Popular instant noodles with convenience appeal but high sodium for daily use.',
        'consumer_watchouts': 'Official nutrition shows around 1000mg sodium per 100g, which is the biggest concern for regular use.',
        'healthier_swap': 'Try oats upma, vegetable poha, or whole-wheat noodles with eggs or paneer',
        'source_url': 'https://www.maggi.in/en/product/maggi-2-minute-noodles/',
        'public_health_reference': 'https://www.maggi.in/en/product/maggi-2-minute-noodles/',
        'calories_per_100g': 384,
        'sugar_per_100g': 1.8,
        'protein_per_100g': 8.2,
        'fat_per_100g': 12.5,
        'sodium_mg_per_100g': 1000,
    },
    {
        'name': 'Coca-Cola Original Taste',
        'brand': 'Coca-Cola',
        'category': 'Soft Drink',
        'ingredient_text': 'Ingredients: carbonated water, sugar, caramel color, phosphoric acid, natural flavourings, caffeine.',
        'image_url': '/static/images/products/coke.svg',
        'short_description': 'Classic cola with high sugar density and very low nutritional value.',
        'consumer_watchouts': 'Per 100ml values are around 42 kcal and 10.6g sugar, so a full bottle quickly adds a heavy sugar load.',
        'healthier_swap': 'Choose plain soda with lemon, coconut water, or unsweetened lime soda',
        'source_url': 'https://www.coca-cola.com/xf/en/brands/coca-cola',
        'public_health_reference': 'https://www.coca-cola.com/gb/en/brands/coca-cola-original-taste',
        'calories_per_100g': 42,
        'sugar_per_100g': 10.6,
        'protein_per_100g': 0,
        'fat_per_100g': 0,
        'sodium_mg_per_100g': 8,
    },
    {
        'name': "Lay's West Indies Hot n Sweet Chilli",
        'brand': "Lay's",
        'category': 'Chips',
        'ingredient_text': 'Ingredients: potato, vegetable oil, palm olein, rice bran oil, seasoning, sugar, iodized salt, acidity regulator, flavour enhancers 627 and 631, natural flavouring.',
        'image_url': '/static/images/products/lays.svg',
        'short_description': 'Crispy chips with flavour enhancers and oil-heavy nutrition.',
        'consumer_watchouts': 'Palm oil use in Lay\'s India became a major public discussion in May 2024 after Food Pharmer highlighted it and PepsiCo said it was trialing new oil blends.',
        'healthier_swap': 'Switch to air-popped makhana, roasted peanuts, or baked potato wedges',
        'source_url': 'https://b2b-kkbsweetsandmore.de/en/products/lays-west-indies-hot-n-sweet-chilli-50g',
        'public_health_reference': 'https://www.moneycontrol.com/news/business/companies/big-win-says-food-pharmer-after-pepsico-decides-to-cut-palm-oil-in-lays-12718953.html',
        'calories_per_100g': 555,
        'sugar_per_100g': 2.0,
        'protein_per_100g': 5.8,
        'fat_per_100g': 35.7,
        'sodium_mg_per_100g': 670,
    },
    {
        'name': 'Amul Taaza Milk',
        'brand': 'Amul',
        'category': 'Dairy',
        'ingredient_text': 'Ingredients: toned milk.',
        'image_url': '/static/images/products/amul.svg',
        'short_description': 'Simple toned milk with decent protein and no added sugar.',
        'consumer_watchouts': 'This is one of the cleaner products in the catalog. The main question is portion and total daily dairy tolerance, not additives.',
        'healthier_swap': 'Already a strong basic choice. Pair it with fruit, oats, or eggs for a fuller meal',
        'source_url': 'https://amul.com/products/amul-taaza-info.php',
        'public_health_reference': 'https://amul.com/products/amul-taaza-info.php',
        'calories_per_100g': 58,
        'sugar_per_100g': 4.7,
        'protein_per_100g': 3.0,
        'fat_per_100g': 3.0,
        'sodium_mg_per_100g': 37,
    },
    {
        'name': "Kellogg's Oats",
        'brand': "Kellogg's",
        'category': 'Breakfast',
        'ingredient_text': 'Ingredients: oats.',
        'image_url': '/static/images/products/oats.svg',
        'short_description': 'Simple oats product with better fiber and satiety than most packaged snacks.',
        'consumer_watchouts': 'Works well when cooked with milk, curd, eggs, or dal. The product itself is clean, but sweet toppings can change the nutrition quickly.',
        'healthier_swap': 'Keep it and improve it with fruit, curd, nuts, or an egg side',
        'source_url': 'https://www.kelloggs.com/en-in/products/oats.html',
        'public_health_reference': 'https://www.kelloggs.com/en-in/products/oats.html',
        'calories_per_100g': 389,
        'sugar_per_100g': 1.0,
        'protein_per_100g': 11.0,
        'fat_per_100g': 8.0,
        'sodium_mg_per_100g': 5,
    },
    {
        'name': 'Britannia Good Day Butter Cookies',
        'brand': 'Britannia',
        'category': 'Biscuits',
        'ingredient_text': 'Ingredients: wheat flour, sugar, palm oil, butter, whole milk powder, raising agents, salt, emulsifiers, natural and artificial flavours.',
        'image_url': '/static/images/products/goodday.svg',
        'short_description': 'Classic tea-time cookie with refined flour, sugar, and palm fat.',
        'consumer_watchouts': 'Tastes harmless because of the butter positioning, but the nutrition still skews toward sugar and fat with limited fiber.',
        'healthier_swap': 'Swap daily tea biscuits for roasted chana, peanuts, or homemade atta toast',
        'source_url': 'https://britannia-international.com/products/product-type/cookies/good-day-butter/',
        'public_health_reference': 'https://www.foodrepo.org/en/products/132200',
        'calories_per_100g': 500,
        'sugar_per_100g': 23.5,
        'protein_per_100g': 5.9,
        'fat_per_100g': 23.5,
        'sodium_mg_per_100g': 320,
    },
    {
        'name': 'Parle-G Original Gluco Biscuits',
        'brand': 'Parle',
        'category': 'Biscuits',
        'ingredient_text': 'Ingredients: wheat flour, sugar, palm oil, invert syrup, leavening agents, salt, skim milk powder, artificial vanilla flavour, emulsifier, preservative.',
        'image_url': '/static/images/products/parleg.svg',
        'short_description': 'Iconic budget biscuit that delivers quick energy but not much satiety or nutrient density.',
        'consumer_watchouts': 'Still a refined biscuit with sugar and palm oil, so it is better as an occasional tea snack than a health food.',
        'healthier_swap': 'Have fruit with peanuts, curd, or boiled chana instead',
        'source_url': 'https://www.foodrepo.org/en/products/136742',
        'public_health_reference': 'https://www.parleproducts.com/',
        'calories_per_100g': 461,
        'sugar_per_100g': 24.8,
        'protein_per_100g': 7.1,
        'fat_per_100g': 12.4,
        'sodium_mg_per_100g': 280,
    },
    {
        'name': 'Cadbury Bournvita',
        'brand': 'Cadbury',
        'category': 'Chocolate Drink Mix',
        'ingredient_text': 'Ingredients: sugar, cereal extracts, cocoa solids, milk solids, vitamins, minerals, emulsifiers, nature-identical flavouring substances.',
        'image_url': '/static/images/products/bournvita.svg',
        'short_description': 'Fortified drink mix with meaningful micronutrient marketing but still a high-sugar product.',
        'consumer_watchouts': 'Food Pharmer\'s 2023 critique centered on sugar content; by December 2023 NDTV reported Bournvita had cut added sugar to about 32.2g per 100g.',
        'healthier_swap': 'Use plain milk with cocoa, nuts, dates, or a smaller portion of drink mix',
        'source_url': 'https://www.ndtv.com/feature/watch-bournvita-reduces-added-sugar-by-14-4-after-criticism-influencer-calls-it-big-win-4733774/amp/1',
        'public_health_reference': 'https://food.ndtv.com/news/icymi-big-win-viral-influencer-on-bournvita-slashing-added-sugar-post-backlash-4751468',
        'calories_per_100g': 380,
        'sugar_per_100g': 32.2,
        'protein_per_100g': 7.0,
        'fat_per_100g': 6.5,
        'sodium_mg_per_100g': 250,
    },
]


class Command(BaseCommand):
    help = 'Seed current ingredient references and predefined products for Smart Food Safety Analyzer.'

    def handle(self, *args, **options):
        for item in INGREDIENT_DATA:
            IngredientReference.objects.update_or_create(name=item['name'], defaults=item)
        for item in PRODUCT_DATA:
            Product.objects.update_or_create(name=item['name'], defaults=item)
        self.stdout.write(self.style.SUCCESS('Updated ingredient references and current product catalog successfully.'))
