# Generated by Django 5.2 on 2026-03-29 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('aliases', models.CharField(blank=True, help_text='Comma-separated aliases.', max_length=255)),
                ('risk_level', models.CharField(choices=[('safe', 'Safe'), ('moderate', 'Moderate'), ('harmful', 'Harmful')], max_length=20)),
                ('score_impact', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('ingredient_text', models.TextField()),
                ('category', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('input_source', models.CharField(default='upload', max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('normalized_ingredients', models.TextField(blank=True)),
                ('health_score', models.PositiveIntegerField(default=0)),
                ('classification', models.CharField(default='Moderate', max_length=20)),
                ('harmful_found', models.TextField(blank=True)),
                ('moderate_found', models.TextField(blank=True)),
                ('safe_found', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analyzer.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
