# Generated by Django 5.2 on 2026-03-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrecord',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='bmi_status',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='daily_calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='diet_preference',
            field=models.CharField(choices=[('balanced', 'Balanced'), ('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non-Vegetarian')], default='balanced', max_length=20),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='healthy_weight_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='healthy_weight_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='height_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='meal_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='protein_target_g',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='target_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='wellness_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='calories_per_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='consumer_watchouts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fat_per_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='healthier_swap',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='protein_per_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='public_health_reference',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sodium_mg_per_100g',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sugar_per_100g',
            field=models.FloatField(default=0),
        ),
    ]
