# Generated by Django 5.2 on 2026-03-29 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_analysisrecord_bmi_analysisrecord_bmi_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserWellnessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('diet_preference', models.CharField(default='balanced', max_length=20)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('bmi_status', models.CharField(blank=True, max_length=60)),
                ('healthy_weight_min', models.FloatField(blank=True, null=True)),
                ('healthy_weight_max', models.FloatField(blank=True, null=True)),
                ('target_weight', models.FloatField(blank=True, null=True)),
                ('daily_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('protein_target_g', models.PositiveIntegerField(blank=True, null=True)),
                ('wellness_summary', models.TextField(blank=True)),
                ('meal_plan', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
